---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: panzer1119-wildcard-staging
  namespace: traefik
spec:
  secretName: panzer1119-wildcard-staging-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
    - "panzer1119.de"
    - "panzer1119.eu"
    - "*.panzer1119.de"
    - "*.panzer1119.eu"
    - "*.argocd-k3s-test.panzer1119.de"
    - "*.argocd-k3s-test.panzer1119.eu"
...
