---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs-single
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: "https://vm-logs.argocd-k3s-test.panzer1119.de"
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-logs-single
    targetRevision: 0.12.4
    helm:
      valuesObject:
        server:
          #TODO replicas, poddisuptionbudget (etc?)
          retentionPeriod: 30d
          persistentVolume:
            size: 20Gi
          ingress:
            enabled: true
            hosts:
              - name: vm-logs.argocd-k3s-test.panzer1119.de
                path:
                  - /
                port: http
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-local-only@kubernetescrd,traefik-authelia@kubernetescrd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoria-logs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
...
