---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-configuration
  namespace: external-dns
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: adguard-configuration
  data:
    - secretKey: url
      remoteRef:
        key: "AdGuard Home"
        property: "URL"
    - secretKey: user
      remoteRef:
        key: "AdGuard Home"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "AdGuard Home"
        property: "password"
...
