---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k8s-stack
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: "https://victoria-metrics.argocd-k3s-test.local.panzer1119.de"
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.66.1
    helm:
      valuesObject:
        alertmanager:
          ingress:
            enabled: true
            hosts:
              - vm-alertmanager.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
        grafana:
          plugins:
            - victoriametrics-metrics-datasource
            - victoriametrics-logs-datasource
          ingress:
            enabled: true
            hosts:
              - vm-grafana.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
        victoria-metrics-operator:
          enabled: false
        vmagent:
          ingress:
            enabled: true
            hosts:
              - vm-agent.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
        vmalert:
          ingress:
            enabled: true
            hosts:
              - vm-alert.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
        vmsingle:
          ingress:
            enabled: true
            hosts:
              - victoria-metrics.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoria-metrics-k8s-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs
      # argocd must also ignore difference during apply stage
      # otherwise it ll silently override changes and cause a problem
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - kind: Secret
      name: vm-operator-validation
      namespace: victoria-metrics-k8s-stack
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vm-operator-admission
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
...
