---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k8s-stack
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: "https://victoria-metrics.argocd-k3s-test.local.panzer1119.de"
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.67.0
    helm:
      valuesObject:
        alertmanager:
          ingress:
            enabled: true
            hosts:
              - vm-alertmanager.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
        grafana:
          plugins:
            - victoriametrics-metrics-datasource
            - victoriametrics-logs-datasource
          ingress:
            enabled: true
            hosts:
              - vm-grafana.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
        victoria-metrics-operator:
          enabled: false
        vmagent:
          ingress:
            enabled: true
            hosts:
              - vm-agent.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
          spec:
            extraArgs:
              promscrape.dropOriginalLabels: "false"
            selectAllByDefault: true
            inlineScrapeConfig: |
              - job_name: traefik
                kubernetes_sd_configs:
                  - role: endpoints
                relabel_configs:
                  - source_labels: [__meta_kubernetes_namespace]
                    action: keep
                    regex: traefik
                  - source_labels: [__meta_kubernetes_endpoints_label_app_kubernetes_io_name]
                    action: keep
                    regex: traefik
                  - source_labels: [__meta_kubernetes_pod_container_port_name]
                    action: keep
                    regex: metrics
        vmalert:
          ingress:
            enabled: true
            hosts:
              - vm-alert.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
        vmsingle:
          ingress:
            enabled: true
            hosts:
              - victoria-metrics.argocd-k3s-test.local.panzer1119.de
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoria-metrics-k8s-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs
      # argocd must also ignore difference during apply stage
      # otherwise it ll silently override changes and cause a problem
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - kind: Secret
      name: vm-operator-validation
      namespace: victoria-metrics-k8s-stack
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vm-operator-admission
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
...
