{
 "title": "Spegel Monitoring Dashboard",
 "description": "A comprehensive Grafana dashboard for monitoring Spegel, focusing on Spegel-specific metrics such as mirror requests, resolve durations, advertised images, and HTTP metrics.",
 "tags": [
  "spegel",
  "kubernetes",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(spegel_advertised_keys, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Spegel Mirror Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mirror Last Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (time() - spegel_mirror_last_success_timestamp_seconds{job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mirror Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(spegel_mirror_requests_total{instance=~\"$instance\"}[30s])) by (cache, source)",
     "legendFormat": "{{cache}} - {{source}}"
    }
   ]
  },
  {
   "title": "Spegel Resolve Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(spegel_resolve_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le, router, instance))",
     "legendFormat": "{{router}} - {{instance}}"
    }
   ]
  },
  { "title": "Advertised Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Advertised Images per Registry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(spegel_advertised_images{instance=~\"$instance\"}) by (registry)",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  {
   "title": "Advertised Image Tags per Registry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(spegel_advertised_image_tags{instance=~\"$instance\"}) by (registry)",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  {
   "title": "Advertised Image Digests per Registry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(spegel_advertised_image_digests{instance=~\"$instance\"}) by (registry)",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  {
   "title": "Advertised Keys per Registry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(spegel_advertised_keys{instance=~\"$instance\"}) by (registry)",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  {
   "title": "Advertised Layers per Registry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(spegel_advertised_keys{instance=~\"$instance\"}) by (registry) - (sum(spegel_advertised_images{instance=~\"$instance\"}) by (registry) or on (registry) vector(0))",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Current In-flight HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_requests_inflight{instance=~\"$instance\"}) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Response Size (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_response_size_bytes_bucket{instance=~\"$instance\"}[30s])) by (le, handler, method, code))",
     "legendFormat": "{{handler}} - {{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le, handler, method, code))",
     "legendFormat": "{{handler}} - {{method}} - {{code}}"
    }
   ]
  }
 ]
}