---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: admin-user
  namespace: victoria-metrics-k8s-stack
spec:
  deletionPolicy: Delete
  refreshInterval: 10m0s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: 1password-connect
  selector:
    secret:
      name: victoria-metrics-k8s-stack-grafana
  data:
    - match:
        secretKey: admin-user
        remoteRef:
          remoteKey: "homelab-argocd-k3s-test-cluster - victoria-metrics-k8s-stack - grafana-admin"
          property: "username"
    - match:
        secretKey: admin-password
        remoteRef:
          remoteKey: "homelab-argocd-k3s-test-cluster - victoria-metrics-k8s-stack - grafana-admin"
          property: "password"
...
