---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freenas-api-smb-config
  namespace: democratic-csi
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: freenas-api-smb-config
    template:
      engineVersion: v2
      data:
        "driver-config-file.yaml": |
          ---
          driver: "freenas-api-smb"
          instance_id:
          httpConnection:
            protocol: "{{ .http_connection_protocol }}"
            host: "{{ .http_connection_host }}"
            port: {{ .http_connection_port }}
            apiKey: "{{ .http_connection_api_key }}"
            allowInsecure: {{ .http_connection_allow_insecure }}
            # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
            # leave unset for auto-detection
            apiVersion: {{ .http_connection_api_version }}
          _private:
            csi:
              volume:
                idTemplate: "{{ `ns-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}--pvc-{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
                deleteStrategy: "retain"
                idHash:
                  #strategy: "crc8"
                  #strategy: "crc16"
                  #strategy: "crc32"
                  strategy: "md5"
                  #strategy: "sha1"
          zfs:
            # can be used to set arbitrary values on the dataset/zvol
            # can use handlebars templates with the parameters from the storage class/CO
            datasetProperties:
              aclmode: restricted
              aclinherit: passthrough
              acltype: nfsv4
              casesensitivity: insensitive

              "org.freenas:description": "CSI - {{ .cluster_short_id }} - {{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
              "democratic-csi:cluster-short-id": "{{ .cluster_short_id }}"
              "democratic-csi:csi.storage.k8s.io-pvc-namespace": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}` }}"
              "democratic-csi:csi.storage.k8s.io-pvc-name": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            #  "org.freenas:description": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            #  "org.freenas:test": "{{ `{{ parameters.foo }}` }}"
            #  "org.freenas:test2": "some value"
            snapshotProperties:
              "org.freenas:description": "CSI - {{ .cluster_short_id }} - {{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
              "democratic-csi:cluster-short-id": "{{ .cluster_short_id }}"
              "democratic-csi:csi.storage.k8s.io-pvc-namespace": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}` }}"
              "democratic-csi:csi.storage.k8s.io-pvc-name": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            #  "org.freenas:key": "value"

            # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
            # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
            # standard volume naming overhead is 46 chars
            # datasetParentName should therefore be 17 chars or less when using TrueNAS 12 or below (SCALE and 13+ do not have the same limits)
            # for work-arounds see https://github.com/democratic-csi/democratic-csi/issues/54
            datasetParentName: "{{ .zfs_global_dataset_parent_name }}/{{ .cluster_short_id }}/smb"
            # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
            # they may be siblings, but neither should be nested in the other
            # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
            detachedSnapshotsDatasetParentName: "{{ .zfs_global_dataset_parent_name }}/{{ .cluster_short_id }}/snaps"
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0770"

            # as appropriate create a dedicated user for smb connections
            # and set this
            datasetPermissionsUser: {{ .zfs_dataset_permission_user }}
            datasetPermissionsGroup: {{ .zfs_dataset_permission_group }}
          
            # CORE
            #datasetPermissionsAclsBinary: setfacl
  
            # SCALE
            datasetPermissionsAclsBinary: nfs4xdr_setfacl
  
            # if using a user other than guest/nobody comment the 'everyone@' acl
            # and uncomment the appropriate block below 
            datasetPermissionsAcls:
              #- "-m everyone@:full_set:fd:allow"
                
              # CORE
              # in CORE you cannot have multiple entries for the same principle
              # or said differently, they are declarative so using -m will replace
              # whatever the current value is for the principle rather than adding a
              # entry in the acl list
              #- "-m g:builtin_users:full_set:fd:allow"
              #- "-m group@:modify_set:fd:allow"
              #- "-m owner@:full_set:fd:allow"
              
              # SCALE
              # https://www.truenas.com/community/threads/get-setfacl-on-scale-with-nfsv4-acls.95231/
              # -s replaces everything
              # so we put this in specific order to mimic the defaults of SCALE when using the api
              - -s group:builtin_users:full_set:fd:allow
              - -a group:builtin_users:modify_set:fd:allow
              - -a group@:modify_set:fd:allow
              - -a owner@:full_set:fd:allow
          smb:
            shareHost: "{{ .smb_share_host }}"
            nameTemplate: "{{ `ns-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}--pvc-{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            namePrefix: "csi-{{ .cluster_short_id }}-"
            nameSuffix: ""
            
            # if any of the shareFoo parameters do not work with your version of FreeNAS
            # simply comment the param (and use the configuration template if necessary)
          
            shareAuxiliaryConfigurationTemplate: |
              #guest ok = yes
              #guest only = yes
            shareHome: false
            shareAllowedHosts: []
            shareDeniedHosts: []
            #shareDefaultPermissions: true
            shareGuestOk: false
            #shareGuestOnly: true
            #shareShowHiddenFiles: true
            shareRecycleBin: true
            shareBrowsable: false
            shareAccessBasedEnumeration: true
            shareTimeMachine: false
            #shareStorageTask:
          ...
  data:
    - secretKey: cluster_short_id
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "Cluster-Short-ID"
    - secretKey: http_connection_protocol
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "Protocol"
    - secretKey: http_connection_host
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "Host"
    - secretKey: http_connection_port
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "Port"
    - secretKey: http_connection_api_key
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "API-Key"
    - secretKey: http_connection_allow_insecure
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "Allow-Insecure"
    - secretKey: http_connection_api_version
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "API-Version"
    - secretKey: zfs_global_dataset_parent_name
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "SMB - ZFS-Global-Dataset-Parent-Name"
    - secretKey: zfs_dataset_permission_user
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "SMB - ZFS-Dataset-Permission-User"
    - secretKey: zfs_dataset_permission_group
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "SMB - ZFS-Dataset-Permission-Group"
    - secretKey: smb_share_host
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "SMB - SMB-Share-Host"
...
