---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freenas-api-smb-freenas-smb-csi-node-stage
  namespace: democratic-csi
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: freenas-api-smb-freenas-smb-csi-node-stage
    template:
      engineVersion: v2
      data:
        mount_flags: "username={{ .username }},password={{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "SMB - Username"
    - secretKey: password
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "SMB - Password"
...
