---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freenas-api-iscsi-freenas-iscsi-csi-node-stage
  namespace: democratic-csi
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: freenas-api-iscsi-freenas-iscsi-csi-node-stage
    template:
      engineVersion: v2
      data:
        node-db.node.session.auth.authmethod: "CHAP"
        node-db.node.session.auth.username: "{{ .user }}"
        node-db.node.session.auth.password: "{{ .password }}"
        node-db.node.session.auth.username_in: "{{ .mutualUser }}"
        node-db.node.session.auth.password_in: "{{ .mutualPassword }}"
  data:
    - secretKey: user
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "ISCSI - Username"
    - secretKey: password
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "ISCSI - Password"
    - secretKey: mutualUser
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "ISCSI - Peer Username"
    - secretKey: mutualPassword
      remoteRef:
        key: "Democratic CSI - FreeNAS API"
        property: "ISCSI - Peer Password"
...
