---
apiVersion: v1
kind: Secret
metadata:
  name: nautik-viewer-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: nautik-viewer
type: kubernetes.io/service-account-token
...