---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nautik-observer-plus
rules:
  # Core read-only access
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - networking.k8s.io
      - policy
      - rbac.authorization.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - networkpolicies
      - nodes
      - pods
      - pods/log
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - statefulsets
    verbs:
      - get
      - list
      - watch

  # Exec into containers
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs: ["create"]

  # Port forwarding
  - apiGroups: [""]
    resources:
      - pods/portforward
    verbs: ["create"] 
...
 