---
apiVersion: v1
kind: Secret
metadata:
  name: nautik-operator-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: nautik-operator
type: kubernetes.io/service-account-token
...