---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: "https://traefik-dashboard.argocd-k3s-test.local.panzer1119.de"
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v38.0.1
    helm:
      valuesObject:
        deployment:
          enabled: true
          replicas: 3
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        ingressRoute:
          dashboard:
            enabled: true
            entryPoints: [ web, websecure ]
            matchRule: Host(`traefik-dashboard.argocd-k3s-test.local.panzer1119.de`) && (Path(`/`) || PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            middlewares:
              - name: redirect-to-https
                namespace: traefik
              - name: authelia
                namespace: traefik
          healthcheck:
            enabled: true
            entryPoints: [ web, websecure ]
            matchRule: Host(`traefik-status.argocd-k3s-test.local.panzer1119.de`)
            middlewares:
              - name: redirect-to-https
                namespace: traefik
        global:
          checkNewVersion: true
          sendAnonymousUsage: false
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--log.level=DEBUG"
        ports:
          web:
            asDefault: false
            http:
              redirections:
                entryPoint:
                  to: :443
                  scheme: https
                  permanent: true
            observability:
              accessLogs: false
              metrics: false
              tracing: false
          websecure:
            asDefault: true
            tls:
              enabled: true
        providers:
          kubernetesCRD:
            enabled: true
            #ingressClass: "traefik-external"
            allowCrossNamespace: true
        service:
          enabled: true
          spec:
            loadBalancerIP: "192.168.7.21"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
...
