---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi-plugin
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: "https://proxmox-csi-plugin-dashboard.argocd-k3s-test.panzer1119.de"
spec:
  project: default
  source:
#    chart: proxmox-csi-plugin
#    repoURL: ghcr.io/panzer1119/charts
#    targetRevision: 0.25.6
    repoURL: https://github.com/Panzer1119/proxmox-csi-plugin.git
    targetRevision: codex/add-real-time-web-visualization-dashboard
    path: charts/proxmox-csi-plugin
    helm:
      valuesObject:
        replicaCount: 1
        existingConfigSecret: proxmox-csi-config
        controller:
          plugin:
            image:
              repository: ghcr.io/panzer1119/proxmox-csi-controller
              pullPolicy: Always
              tag: sha-f50538bb2d58419fea1cef8830e3a8617abae205
        node:
          plugin:
            image:
              repository: ghcr.io/panzer1119/proxmox-csi-node
              pullPolicy: Always
              tag: sha-f50538bb2d58419fea1cef8830e3a8617abae205
#        dashboard:
#          enabled: true
#          #address: ":8088"
#          #refreshInterval: 15s
#          #port: 8088
#          ingress:
#            enabled: true
#            className: traefik
#            annotations:
#              traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd,traefik-local-only@kubernetescrd
#            hosts:
#              - host: proxmox-csi-plugin-dashboard.argocd-k3s-test.panzer1119.de
#                paths:
#                  - path: /
#                    pathType: ImplementationSpecific
        metrics:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: csi-proxmox
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
...
