---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-ultra-fast-zfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: "xfs"
  storage: "ultra-fast-zfs"
  ssd: "true"
  aio: "io_uring"
  cache: "none"
  backup: "false"
  replicate: "false"
  vmID: "30002"
  volumeNameNamespaceUUID: "caf1d440-a6a8-4574-9865-3b6d426b80ce"
#  volumeNameTemplate: 'vol-{{ .VolumeNameUUID }}' # Use this for production
#  volumeNameTemplate: 'ns-{{ .PVCNamespace }}-pvc-{{ .PVCName }}' # Use this for testing
  volumeNameTemplate: 'vol-{{ .VolumeNameUUID }}-ns-{{ .PVCNamespace }}-pvc-{{ .PVCName }}' # Use this for development
#  volumeNameTemplate: 'vol-{{ .VolumeNameUUID }}-ns-{{ .PVCNamespace }}' # Use this for development
mountOptions:
  - noatime
...
