---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-ultra-fast-zfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: "xfs"
  storage: "ultra-fast-zfs"
  ssd: "true"
  aio: "io_uring"
  cache: "none"
  backup: "false"
  replicate: "false"
  vmid: "30002"
mountOptions:
  - noatime
...
