---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.20.3
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true
        replicaCount: 3
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        namespace: cert-manager
        dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
        dns01RecursiveNameserversOnly: true
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - "1.1.1.1"
            - "8.8.8.8"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
...
