---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: cloudflare-api-token
  data:
    - secretKey: secret
      remoteRef:
        key: "Cloudflare API Token - homelab-argocd-k3s-test-cluster"
        property: "Anmeldedaten"
...
