---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-configuration
  namespace: external-dns
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: unifi-configuration
  data:
    - secretKey: UNIFI_HOST
      remoteRef:
        key: "UniFi - external-dns - homelab-argocd-k3s-test-cluster"
        property: "URL"
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: "UniFi - external-dns - homelab-argocd-k3s-test-cluster"
        property: "credential"
...
